[package]
name = "morse"
version = "0.1.0"
edition = "2021"
description = "Convert ASCII text to Morse code audio and text."
license = "Unlicense"

[dependencies]
clap = {version = "4.5.21", features = ["derive"]}
lazy_static = "1.5"
